theme: jekyll-theme-slate
title: Curbing Timeouts for TCP-Incast in Data Centers via A Cross-Layer Faster Recovery Mechanism
description: This project aims at developing an hypervisor-based timely TCP restransmission scheme to improve TCP application perforamcne in data centers
author: Ahmed MOHAMED ABDELMONIEM SAYED
author_email: ahmedcs982@gmail.com
